version: "3"
services:
  jupyter:
    image: jupyter/pyspark-notebook
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - 8888:8888
    volumes:
      - ./work:/home/jovyan/work
    depends_on:
      - database
    environment:
      - DATABASE_URL=jdbc:mysql://database/doximity
    networks:
      - frontend
      - backend
  database:
    image: mysql:5.6
    ports:
      - 3306
    volumes:
      - database:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=doximity
    networks:
      - backend
volumes:
  database:
networks:
  frontend:
  backend:
